CREATE DATABASE groupbyhavingdb;
use groupbyhavingdb;

-- 1. Find the total sales for each product category.

SELECT category_id, SUM(sales_amount) AS total_sales
FROM sales
GROUP BY category_id;

-- 2. Retrieve departments with an average salary greater than 50,000.

select dept,avg(salary) AS Average_salary
from employees
group by dept
having avg(salary)>50000;
-- i had forgotten writing alias and having clause

-- 3. Count the number of employees in each department, but only include departments with more than 10 employees.

select dept_id, count(emp) AS employee_count
from records
group by dept_id
having count(emp)>10;


-- 4. Find customers who placed more than 5 orders.

select customer, COUNT(order_id) AS total_orders
from order_details_table
group by customer
having count(order_id)>5;


-- YOU FORGET ALIAS A LOT

-- 5. Identify products with total sales exceeding $10,000.
select products, sum(order_money) as total_sales
from order_table
group by products
having sum(order_money)>10000;


-- 6. List cities with more than 2 customers, sorted by the number of customers.

select cities, COUNT(customer_id) as customer_count
from customer_table
group by cities
having count(customer_id)>2
order by customer_count DESC;

-- 7. Find the maximum order amount for each customer, but only include customers with total orders exceeding $5,000.

select customer_id, max(order_money) as max_order, sum(order_money) as total_order_money 
from orders
group by customer_id
having sum(order_money)>5000;

-- 8. Show the total revenue generated by each salesperson who sold more than 100 items.

select salesperson, count(sales_id) as items_sold, SUM(sales_money) as total_revenue
from sales
group by salesperson
having count(sales_id)>100;

